- name: configure cisco
  ios_config:
    host: "{{ ansible_host }}"
    parents: "{{ item.parent | default(omit) }}"
    lines: "{{ item.lines | default(omit) }}"
    before: "{{ item.before | default(omit) }}"
    match: line
  with_items: "{{ config }}"
